### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by wulas09763** [SadmanSakib93/Federated-Learning-Keras#1]
Hello, thank you for providing such a good code, can you provide an example of a dataset(CSV)?  
This will give me a better understanding of the code, thank you.

**Comment by SadmanSakib93** [comment]
![image](https://user-images.githubusercontent.com/27827295/149410097-ef0bd7da-3da8-4fc1-aa70-f7e343b1d061.png)

Hi, here is a sample dataset screenshot. So, basically, the first column is your class label (defined as "label"). The rest of the columns are your dependent features of the dataset. For example, in this picture, there are 20 features denoted as A1 to A20. Note that, all the features are numerical features in the CSV file. If you have some categorical features, you have to perform One hot encoding/Label encoding to make them numbers, and then after you can run the program! Hope this helps.
