### ISSUE TITLE
Questions about  code

### ISSUE THREAD

**Issue by wulas09763** [SadmanSakib93/Federated-Learning-Keras#2]
Hello, after reading your code, I have a question, why do you need to store the model again at the end, the previous for iterationNo in range(1,numOfIterations+1) loop has been updated and stored deepModel, I think here  The stored model is the model of the above history retraining model. This model has nothing to do with the above for iterationNo in range(1, numOfIterations+1) loop? May I ask if my understanding is wrong, thank you.
![qs drawio](https://user-images.githubusercontent.com/77091983/150841954-3bbdc851-9062-4fdf-9ab1-b6ba70796e87.png)

**Comment by SadmanSakib93** [comment]
Your understanding is correct and also I believe saving the model here is not really necessary. Thanks for bringing this to my attention. This line is redundant here I think. Hope this clarifies the issue.

**Comment by wulas09763** [comment]
Thank you for your willingness to help me.
